### ISSUE TITLE
ElasticSearch issue

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/engage-docker#4]
Error in bringing up es01

```
es01 exited with code 1
docker-init_1    | Waiting for elasticsearch to start
docker-init_1    | Waiting for elasticsearch to start
docker-init_1    | Waiting for elasticsearch to start
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.002s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.002s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.003s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.003s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.003s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.003s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01             | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
es01             | output:
es01             | [0.001s][error][logging] Error opening log file 'logs/gc.log': Permission denied
es01             | [0.001s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
es01             | error:
es01             | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01             | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
es01             | Error: Could not create the Java Virtual Machine.
es01             | Error: A fatal exception has occurred. Program will exit.
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es01             | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es01             | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
docker-init_1    | Waiting for elasticsearch to start
```

**Comment by TeddyCr** [comment]
@eselkin are you able to show the file permission inside the `es01` container?

```
docker exec -it es01 sh
ls -l logs/
```
I am wondering if it could just be a user permission issue (as shown in the error message) where the user bringing up the container does have permission to write into this log file.

**Comment by eselkin** [comment]
I can't exec into it because it keeps restarting. Let me try bringing it up by itself as a container with docker.

**Comment by eselkin** [comment]
What is the es manifest in bringing up the container? I've given it all the env variables.

**Comment by TeddyCr** [comment]
@eselkin what do you mean by 

> What is the es manifest in bringing up the container?

**Comment by eselkin** [comment]
<img width="471" alt="Screen Shot 2019-11-16 at 4 12 38 PM" src="https://user-images.githubusercontent.com/5606931/69000983-0fb22c00-088c-11ea-8f00-ddd49c8c3ed4.png">

**Comment by TeddyCr** [comment]
Could you run  `ls -lah` 1 level up? 
Basically it does not write anything inside the `logs` folders.

**Comment by eselkin** [comment]
I can't tell if it ever writes anything in the logs directory because I can't access the `docker-compose` container, just running it on the AWS host with `docker run -e "discovery.type=single-node" -e "node.name=es01" -e "network.host=_site_" -e "bootstrap.memory_lock=true" -e "ES_JAVA_OPTS=-Xms256m -Xmx256m" -it docker.elastic.co/elasticsearch/elasticsearch:7.3.0  /bin/sh`

What's the entrypoint that gets run on the compose `es01` container?

<img width="1280" alt="Screen Shot 2019-11-18 at 11 53 02 AM" src="https://user-images.githubusercontent.com/5606931/69086284-1f03b780-09fb-11ea-9ff2-2dfdb70aaf73.png">

**Comment by TeddyCr** [comment]
The user may be the issue. It shows `root` on my end.
![Screen Shot 2019-11-18 at 12 17 55 PM](https://user-images.githubusercontent.com/13626425/69089935-8884c580-09fd-11ea-8ee0-64eb29ee1a20.png)

**Comment by eselkin** [comment]
Let me see about mounting the virtual directories

**Comment by eselkin** [comment]
Ok, mounted the volumes and I get `root:root` for `/usr/share/elasticsearch/logs` ... And it lets me write in that directory... but I'm not sure what the user is when it runs the entrypoint, it could be elasticsearch:elasticsearch

**Comment by eselkin** [comment]
What is the entrypoint script that gets run on `docker-compose up` on es01?

**Comment by eselkin** [comment]
I figured it out... your directories you're mounting need to be chowned `1000:1000` the elasticsearch user id and group id.

**Comment by eselkin** [comment]
See #5

**Comment by TeddyCr** [comment]
@eselkin are you able to post the fix you made (where you added the `chown -R 1000:1000` in the compose fille
